/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Address;
import javax.swing.JOptionPane;

/**
 *
 * @author gagan
 */
public class CreateLocalAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateLocalAddressJPanel
     */
    Address localaddress;
    public CreateLocalAddressJPanel(Address a) {
        initComponents();
        localaddress = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCreateLocal = new javax.swing.JLabel();
        lblLocalFirstName = new javax.swing.JLabel();
        lblLocalSurname = new javax.swing.JLabel();
        lblLocalStreetName = new javax.swing.JLabel();
        lblLocalUnitNumber = new javax.swing.JLabel();
        lblLocalCity = new javax.swing.JLabel();
        fieldLocalFirstName = new javax.swing.JTextField();
        fieldLocalSurname = new javax.swing.JTextField();
        fieldLocalStreetName = new javax.swing.JTextField();
        fieldLocalUnitNumber = new javax.swing.JTextField();
        fieldLocalCity = new javax.swing.JTextField();
        btnLocalSave = new javax.swing.JButton();
        lblLocalZipCode = new javax.swing.JLabel();
        fieldLocalZipCode = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        lblCreateLocal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateLocal.setText("Create Local Address");

        lblLocalFirstName.setText("First Name");

        lblLocalSurname.setText("Surname");

        lblLocalStreetName.setText("Street Name");

        lblLocalUnitNumber.setText("Unit Number");

        lblLocalCity.setText("City");

        btnLocalSave.setText("Save");
        btnLocalSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalSaveActionPerformed(evt);
            }
        });

        lblLocalZipCode.setText("Zip Code");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLocalSave)
                .addGap(223, 223, 223))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLocalUnitNumber)
                    .addComponent(lblLocalFirstName)
                    .addComponent(lblLocalCity)
                    .addComponent(lblLocalStreetName)
                    .addComponent(lblLocalSurname)
                    .addComponent(lblLocalZipCode))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldLocalZipCode)
                    .addComponent(lblCreateLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldLocalFirstName)
                    .addComponent(fieldLocalSurname)
                    .addComponent(fieldLocalUnitNumber)
                    .addComponent(fieldLocalCity)
                    .addComponent(fieldLocalStreetName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCreateLocal)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalFirstName)
                    .addComponent(fieldLocalFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalSurname)
                    .addComponent(fieldLocalSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalStreetName)
                    .addComponent(fieldLocalStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalUnitNumber)
                    .addComponent(fieldLocalUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalCity)
                    .addComponent(fieldLocalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLocalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocalZipCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnLocalSave)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocalSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalSaveActionPerformed
        // TODO add your handling code here:
        // Step 1: Collect text from the field
        
        String firstName = fieldLocalFirstName.getText();
        String surName = fieldLocalSurname.getText();
        String streetName = fieldLocalStreetName.getText();
        String unitNumber = fieldLocalUnitNumber.getText();
        String city = fieldLocalCity.getText();
        String zipCode = fieldLocalZipCode.getText();
        
        // Step 2: Put those information into Person
        
        localaddress.setFirstName(firstName);
        localaddress.setSurName(surName);
        localaddress.setStreetName(streetName);
        localaddress.setUnitNumber(unitNumber);
        localaddress.setCity(city);
        localaddress.setZipCode(zipCode);
        
        // Step 3: Set a little pop-up message
        JOptionPane.showMessageDialog(this, "Successfully Solved");
        
        // Step 4: Clear text after save
        fieldLocalFirstName.setText("");
        fieldLocalSurname.setText("");
        fieldLocalStreetName.setText("");
        fieldLocalUnitNumber.setText("");
        fieldLocalCity.setText("");
        fieldLocalZipCode.setText("");
    }//GEN-LAST:event_btnLocalSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocalSave;
    private javax.swing.JTextField fieldLocalCity;
    private javax.swing.JTextField fieldLocalFirstName;
    private javax.swing.JTextField fieldLocalStreetName;
    private javax.swing.JTextField fieldLocalSurname;
    private javax.swing.JTextField fieldLocalUnitNumber;
    private javax.swing.JTextField fieldLocalZipCode;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCreateLocal;
    private javax.swing.JLabel lblLocalCity;
    private javax.swing.JLabel lblLocalFirstName;
    private javax.swing.JLabel lblLocalStreetName;
    private javax.swing.JLabel lblLocalSurname;
    private javax.swing.JLabel lblLocalUnitNumber;
    private javax.swing.JLabel lblLocalZipCode;
    // End of variables declaration//GEN-END:variables
}
