/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.BankAccount;
import javax.swing.JOptionPane;

/**
 *
 * @author gagan
 */
public class CreateBankAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateBankAccountJPanel
     */
    BankAccount bankAccount;
    public CreateBankAccountJPanel(BankAccount b) {
        initComponents();
        bankAccount = b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCreateBank = new javax.swing.JLabel();
        lblBankFirstName = new javax.swing.JLabel();
        lblBankSurname = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        lblDebitAmount = new javax.swing.JLabel();
        lblCreditAmount = new javax.swing.JLabel();
        fieldBankFirstName = new javax.swing.JTextField();
        fieldBankSurname = new javax.swing.JTextField();
        fieldAccountType = new javax.swing.JTextField();
        fieldDebitAmount = new javax.swing.JTextField();
        fieldCreditAmount = new javax.swing.JTextField();
        btnBankSave = new javax.swing.JButton();
        lblBalanceAmount = new javax.swing.JLabel();
        fieldBalanceAmount = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCreateBank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateBank.setText("Create Bank Account");

        lblBankFirstName.setText("First Name");

        lblBankSurname.setText("Surname");

        lblAccountType.setText("Account Type");

        lblDebitAmount.setText("Debit Amount");

        lblCreditAmount.setText("Credit Amount");

        btnBankSave.setText("Save");
        btnBankSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBankSaveActionPerformed(evt);
            }
        });

        lblBalanceAmount.setText("Balance Amount");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBankSave)
                .addGap(223, 223, 223))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDebitAmount)
                    .addComponent(lblBankFirstName)
                    .addComponent(lblCreditAmount)
                    .addComponent(lblAccountType)
                    .addComponent(lblBankSurname)
                    .addComponent(lblBalanceAmount))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldBalanceAmount)
                    .addComponent(lblCreateBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldBankFirstName)
                    .addComponent(fieldBankSurname)
                    .addComponent(fieldDebitAmount)
                    .addComponent(fieldCreditAmount)
                    .addComponent(fieldAccountType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCreateBank)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankFirstName)
                    .addComponent(fieldBankFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankSurname)
                    .addComponent(fieldBankSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountType)
                    .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDebitAmount)
                    .addComponent(fieldDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditAmount)
                    .addComponent(fieldCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBalanceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBalanceAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnBankSave)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBankSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBankSaveActionPerformed
        // TODO add your handling code here:
        // Step 1: Collect text from the field
        
        String firstName = fieldBankFirstName.getText();
        String surName = fieldBankSurname.getText();
        String accountType = fieldAccountType.getText();
        String debitAmount = fieldDebitAmount.getText();
        String creditAmount = fieldCreditAmount.getText();
        String balanceAmount = fieldBalanceAmount.getText();
        
        // Step 2: Put those information into Person
        
        bankAccount.setFirstName(firstName);
        bankAccount.setSurName(surName);
        bankAccount.setAccountType(accountType);
        bankAccount.setDebitAmnt(debitAmount);
        bankAccount.setCreditAmnt(creditAmount);
        bankAccount.setBalance(balanceAmount);
        
        // Step 3: Set a little pop-up message
        JOptionPane.showMessageDialog(this, "Successfully Saved");
        
        // Step 4: Clear text after save
        fieldBankFirstName.setText("");
        fieldBankSurname.setText("");
        fieldAccountType.setText("");
        fieldDebitAmount.setText("");
        fieldCreditAmount.setText("");
        fieldBalanceAmount.setText("");
  
    }//GEN-LAST:event_btnBankSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBankSave;
    private javax.swing.JTextField fieldAccountType;
    private javax.swing.JTextField fieldBalanceAmount;
    private javax.swing.JTextField fieldBankFirstName;
    private javax.swing.JTextField fieldBankSurname;
    private javax.swing.JTextField fieldCreditAmount;
    private javax.swing.JTextField fieldDebitAmount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblBalanceAmount;
    private javax.swing.JLabel lblBankFirstName;
    private javax.swing.JLabel lblBankSurname;
    private javax.swing.JLabel lblCreateBank;
    private javax.swing.JLabel lblCreditAmount;
    private javax.swing.JLabel lblDebitAmount;
    // End of variables declaration//GEN-END:variables
}
