/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.BankAccount;
import Model.Person;

/**
 *
 * @author gagan
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Person person;
    Address homeAddress;
    Address localAddress;
    BankAccount bankAccount;
    public MainJFrame() {
        initComponents();
        person = new Person();
        homeAddress = new Address();
        localAddress = new Address();
        bankAccount = new BankAccount();
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCreatePerson = new javax.swing.JButton();
        btnViewPerson = new javax.swing.JButton();
        btnCreateHomeAddress = new javax.swing.JButton();
        btnViewHomeAddress = new javax.swing.JButton();
        btnCreateLocalAddress = new javax.swing.JButton();
        btnViewLocalAddress = new javax.swing.JButton();
        btnCreateBankAccount = new javax.swing.JButton();
        btnViewBankAccount = new javax.swing.JButton();
        lblPersonProfile = new javax.swing.JLabel();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(255, 204, 204));
        controlPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCreatePerson.setText("Create Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnViewPerson.setText("View Person");
        btnViewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPersonActionPerformed(evt);
            }
        });

        btnCreateHomeAddress.setText("Create Home Address");
        btnCreateHomeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHomeAddressActionPerformed(evt);
            }
        });

        btnViewHomeAddress.setText("View Home Address");
        btnViewHomeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHomeAddressActionPerformed(evt);
            }
        });

        btnCreateLocalAddress.setText("Create Local Address");
        btnCreateLocalAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLocalAddressActionPerformed(evt);
            }
        });

        btnViewLocalAddress.setText("View Local Address");
        btnViewLocalAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLocalAddressActionPerformed(evt);
            }
        });

        btnCreateBankAccount.setText("Create Bank Account");
        btnCreateBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBankAccountActionPerformed(evt);
            }
        });

        btnViewBankAccount.setText("View Bank Account");
        btnViewBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBankAccountActionPerformed(evt);
            }
        });

        lblPersonProfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPersonProfile.setText("Person Profile");

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCreateHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreatePerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateLocalAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewLocalAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateBankAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewBankAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblPersonProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblPersonProfile)
                .addGap(18, 18, 18)
                .addComponent(btnCreatePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewPerson)
                .addGap(18, 18, 18)
                .addComponent(btnCreateHomeAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewHomeAddress)
                .addGap(18, 18, 18)
                .addComponent(btnCreateLocalAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewLocalAddress)
                .addGap(18, 18, 18)
                .addComponent(btnCreateBankAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewBankAccount)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        // Step 1: Instantiate the CreateJPanel
        CreatePersonJPanel createPersonJPanel = new CreatePersonJPanel(person);
        
        // Step 2: Switch
        splitPane.setRightComponent(createPersonJPanel);
   
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnCreateHomeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHomeAddressActionPerformed
        // TODO add your handling code here:
        // Step 1: Instantiate the CreateHomeAddressJPanel
        CreateHomeAddressJPanel createHomeAddressJPanel = new CreateHomeAddressJPanel(homeAddress);
        // Step 2: switch
        splitPane.setRightComponent(createHomeAddressJPanel);


    }//GEN-LAST:event_btnCreateHomeAddressActionPerformed

    private void btnCreateLocalAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLocalAddressActionPerformed
        // TODO add your handling code here:
        // Step 1: Instantiate the CreateLocalAddressJPanel
        CreateLocalAddressJPanel createLocalAddressJPanel = new CreateLocalAddressJPanel(localAddress);
        // Step 2: switch
        splitPane.setRightComponent(createLocalAddressJPanel);

    }//GEN-LAST:event_btnCreateLocalAddressActionPerformed

    private void btnCreateBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBankAccountActionPerformed
        // TODO add your handling code here:
        // Step 1: Instantiate the CreateBankAccountJPanel
        CreateBankAccountJPanel createBankAccountJPanel = new CreateBankAccountJPanel(bankAccount);
        // Step 2: switch
        splitPane.setRightComponent(createBankAccountJPanel);

    }//GEN-LAST:event_btnCreateBankAccountActionPerformed

    private void btnViewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPersonActionPerformed
        // TODO add your handling code here:
        // Step 1: Instantiate the ViewPersonJPanel
        ViewPersonJPanel viewPersonJPanel =new ViewPersonJPanel(person);
        //Step 2: switch
        splitPane.setRightComponent(viewPersonJPanel);
    }//GEN-LAST:event_btnViewPersonActionPerformed

    private void btnViewHomeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHomeAddressActionPerformed
        // TODO add your handling code here:
        // Step 1: Instantiate the ViewHomeAddressJPanel
        ViewHomeAddressJPanel viewHomeAddressJPanel =new ViewHomeAddressJPanel(homeAddress);
        //Step 2: switch
        splitPane.setRightComponent(viewHomeAddressJPanel);
    }//GEN-LAST:event_btnViewHomeAddressActionPerformed

    private void btnViewLocalAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLocalAddressActionPerformed
        // TODO add your handling code here:
        // Step 1: Instantiate the ViewLocalAddressJPanel
        ViewLocalAddressJPanel viewLocalAddressJPanel =new ViewLocalAddressJPanel(localAddress);
        //Step 2: switch
        splitPane.setRightComponent(viewLocalAddressJPanel);
    }//GEN-LAST:event_btnViewLocalAddressActionPerformed

    private void btnViewBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBankAccountActionPerformed
        // TODO add your handling code here:
        // Step 1: Instantiate the ViewBankAccountJPanel
        ViewBankAccountJPanel viewBankAccountJPanel = new ViewBankAccountJPanel(bankAccount);
        // Step 2: switch
        splitPane.setRightComponent(viewBankAccountJPanel);
    }//GEN-LAST:event_btnViewBankAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBankAccount;
    private javax.swing.JButton btnCreateHomeAddress;
    private javax.swing.JButton btnCreateLocalAddress;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnViewBankAccount;
    private javax.swing.JButton btnViewHomeAddress;
    private javax.swing.JButton btnViewLocalAddress;
    private javax.swing.JButton btnViewPerson;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel lblPersonProfile;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
