/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Address;

/**
 *
 * @author gagan
 */
public class ViewLocalAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewLocalAddressJPanel
     */
    Address address;
    public ViewLocalAddressJPanel(Address a) {
        initComponents();
        address = a;
        display();
    }
    
    private void display() {
        fieldLocalFirstName.setText(address.getFirstName());
        fieldLocalSurname.setText(address.getSurName());
        fieldLocalStreetName.setText(address.getStreetName());
        fieldLocalUnitNumber.setText(address.getUnitNumber());
        fieldLocalCity.setText(address.getCity());
        fieldLocalZipCode.setText(address.getZipCode());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCreateLocal = new javax.swing.JLabel();
        lblLocalFirstName = new javax.swing.JLabel();
        lblLocalSurname = new javax.swing.JLabel();
        lblLocalStreetName = new javax.swing.JLabel();
        lblLocalUnitNumber = new javax.swing.JLabel();
        lblLocalCity = new javax.swing.JLabel();
        fieldLocalFirstName = new javax.swing.JTextField();
        fieldLocalSurname = new javax.swing.JTextField();
        fieldLocalStreetName = new javax.swing.JTextField();
        fieldLocalUnitNumber = new javax.swing.JTextField();
        fieldLocalCity = new javax.swing.JTextField();
        lblLocalZipCode = new javax.swing.JLabel();
        fieldLocalZipCode = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCreateLocal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateLocal.setText("View Local Address");

        lblLocalFirstName.setText("First Name");

        lblLocalSurname.setText("Surname");

        lblLocalStreetName.setText("Street Name");

        lblLocalUnitNumber.setText("Unit Number");

        lblLocalCity.setText("City");

        lblLocalZipCode.setText("Zip Code");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLocalUnitNumber)
                    .addComponent(lblLocalFirstName)
                    .addComponent(lblLocalCity)
                    .addComponent(lblLocalStreetName)
                    .addComponent(lblLocalSurname)
                    .addComponent(lblLocalZipCode))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldLocalZipCode)
                    .addComponent(lblCreateLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldLocalFirstName)
                    .addComponent(fieldLocalSurname)
                    .addComponent(fieldLocalUnitNumber)
                    .addComponent(fieldLocalCity)
                    .addComponent(fieldLocalStreetName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCreateLocal)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalFirstName)
                    .addComponent(fieldLocalFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalSurname)
                    .addComponent(fieldLocalSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalStreetName)
                    .addComponent(fieldLocalStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalUnitNumber)
                    .addComponent(fieldLocalUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalCity)
                    .addComponent(fieldLocalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLocalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocalZipCode))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldLocalCity;
    private javax.swing.JTextField fieldLocalFirstName;
    private javax.swing.JTextField fieldLocalStreetName;
    private javax.swing.JTextField fieldLocalSurname;
    private javax.swing.JTextField fieldLocalUnitNumber;
    private javax.swing.JTextField fieldLocalZipCode;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCreateLocal;
    private javax.swing.JLabel lblLocalCity;
    private javax.swing.JLabel lblLocalFirstName;
    private javax.swing.JLabel lblLocalStreetName;
    private javax.swing.JLabel lblLocalSurname;
    private javax.swing.JLabel lblLocalUnitNumber;
    private javax.swing.JLabel lblLocalZipCode;
    // End of variables declaration//GEN-END:variables

}
