/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.BankAccount;

/**
 *
 * @author gagan
 */
public class ViewBankAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewBankAccountJPanel
     */
    BankAccount bankAccount;
    public ViewBankAccountJPanel(BankAccount b) {
        initComponents();
        bankAccount = b;
        display();
    }

    private void display() {
        fieldBankFirstName.setText(bankAccount.getFirstName());
        fieldBankSurname.setText(bankAccount.getSurName());
        fieldDebitAmount.setText(bankAccount.getDebitAmnt());
        fieldCreditAmount.setText(bankAccount.getCreditAmnt());
        fieldBalanceAmount.setText(bankAccount.getBalance());
        fieldAccountType.setText(bankAccount.getAccountType());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCreateBank = new javax.swing.JLabel();
        lblBankFirstName = new javax.swing.JLabel();
        lblBankSurname = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        lblDebitAmount = new javax.swing.JLabel();
        lblCreditAmount = new javax.swing.JLabel();
        fieldBankFirstName = new javax.swing.JTextField();
        fieldBankSurname = new javax.swing.JTextField();
        fieldAccountType = new javax.swing.JTextField();
        fieldDebitAmount = new javax.swing.JTextField();
        fieldCreditAmount = new javax.swing.JTextField();
        lblBalanceAmount = new javax.swing.JLabel();
        fieldBalanceAmount = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCreateBank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateBank.setText("View Bank Account");

        lblBankFirstName.setText("First Name");

        lblBankSurname.setText("Surname");

        lblAccountType.setText("Account Type");

        lblDebitAmount.setText("Debit Amount");

        lblCreditAmount.setText("Credit Amount");

        lblBalanceAmount.setText("Balance Amount");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDebitAmount)
                    .addComponent(lblBankFirstName)
                    .addComponent(lblCreditAmount)
                    .addComponent(lblAccountType)
                    .addComponent(lblBankSurname)
                    .addComponent(lblBalanceAmount))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldBalanceAmount)
                    .addComponent(lblCreateBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldBankFirstName)
                    .addComponent(fieldBankSurname)
                    .addComponent(fieldDebitAmount)
                    .addComponent(fieldCreditAmount)
                    .addComponent(fieldAccountType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCreateBank)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankFirstName)
                    .addComponent(fieldBankFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankSurname)
                    .addComponent(fieldBankSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountType)
                    .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDebitAmount)
                    .addComponent(fieldDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditAmount)
                    .addComponent(fieldCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBalanceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBalanceAmount))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAccountType;
    private javax.swing.JTextField fieldBalanceAmount;
    private javax.swing.JTextField fieldBankFirstName;
    private javax.swing.JTextField fieldBankSurname;
    private javax.swing.JTextField fieldCreditAmount;
    private javax.swing.JTextField fieldDebitAmount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblBalanceAmount;
    private javax.swing.JLabel lblBankFirstName;
    private javax.swing.JLabel lblBankSurname;
    private javax.swing.JLabel lblCreateBank;
    private javax.swing.JLabel lblCreditAmount;
    private javax.swing.JLabel lblDebitAmount;
    // End of variables declaration//GEN-END:variables


}
