
import Library.Branches.Branch;
import Library.Branches.BranchDirectory;
import Library.Library;
import Library.Profiles.AdminProfile;
import Library.Profiles.BranchManagerProfile;
import Library.Profiles.CustomerProfile;
import Library.Profiles.Profile;
import Library.UserAccounts.UserAccount;
import Library.UserAccounts.UserAccountDirectory;
import UserAccountSignUp.UserAccountSignUpJPanel;
import UserInterface.Admin.ControlPanelAdmin;
import UserInterface.BranchManager.ControlPanelBranchManager;
import UserInterface.Customer.ControlPanelCustomer;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author gagan
 */
public class LoginScreenPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreenPanel
     */
    LibrarySystem ls;
    JPanel mainWorkArea;
    
    public LoginScreenPanel(JPanel mainWorkArea) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.ls = ConfigureALibraryManagement.initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();

        title.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        title.setText("Library System Login");

        lblUserName.setText("Username");

        lblPass.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnSignUp.setText("SignUp");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(231, 231, 231)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                            .addGap(75, 75, 75)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(txtUserName)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                    .addContainerGap(232, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUserName)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPass)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addComponent(btnLogin)
                    .addGap(18, 18, 18)
                    .addComponent(btnSignUp)
                    .addContainerGap(173, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        // TODO add your handling code here:
        String un = txtUserName.getText();
        String pw = txtPass.getText();

        UserAccountDirectory uad = this.ls.getUserAccountDirectory();
        UserAccount useraccount = uad.AuthenticateUser(un, pw);
        if (useraccount == null) {
            JOptionPane.showMessageDialog(mainWorkArea, "No user found");
            return;
        }
        
        txtUserName.setText("");
        txtPass.setText("");

        ControlPanelAdmin controlPanelAdmin;
        ControlPanelBranchManager controlPanelBranchManager;
        ControlPanelCustomer  controlPanelCustomer;

        String r = useraccount.getRole();
        Profile profile = useraccount.getAssociatedPersonProfile();

        if (profile instanceof AdminProfile) {
            controlPanelAdmin = new ControlPanelAdmin(this.ls.getUserAccountDirectory(), this.ls.branchDirectory, this.mainWorkArea);
//            this.mainWorkArea.removeAll();    
//            this.mainWorkArea.add("admin", controlPanelAdmin);
            CardLayout cardLayout = new CardLayout();
            this.mainWorkArea.setLayout(cardLayout);
            this.mainWorkArea.add(controlPanelAdmin);
            cardLayout.next(this.mainWorkArea);
        } else if (profile instanceof BranchManagerProfile) {
            Branch branch = null;
            for(Branch b: this.ls.getBranchDirectory().getBranchlist()) {
                if(b.getManager() != null && b.getManager().equals(profile)) {
                    branch = b;
                }
            }
                
            if(branch != null) {
                controlPanelBranchManager = new ControlPanelBranchManager(this.mainWorkArea, branch);
//            this.mainWorkArea.removeAll();    
//            this.mainWorkArea.add("admin", controlPanelAdmin);
                CardLayout cardLayout = new CardLayout();
                this.mainWorkArea.setLayout(cardLayout);
                this.mainWorkArea.add(controlPanelBranchManager);
                cardLayout.next(this.mainWorkArea);
            }
            
        } else if(profile instanceof CustomerProfile){
            UserAccount customer = this.ls.userAccountDirectory.findUserAccount(profile.getPerson().getPersonId());
            controlPanelCustomer = new ControlPanelCustomer(this.mainWorkArea, this.ls.branchDirectory, (CustomerProfile) customer.getAssociatedPersonProfile());
            CardLayout cardLayout = new CardLayout();
            this.mainWorkArea.setLayout(cardLayout);
            this.mainWorkArea.add(controlPanelCustomer);
            cardLayout.next(this.mainWorkArea);
        }
       
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        UserAccountSignUpJPanel uasujp = new UserAccountSignUpJPanel(this.mainWorkArea, this.ls.getUserAccountDirectory());
        CardLayout cardLayout = new CardLayout();
        this.mainWorkArea.setLayout(cardLayout);
        this.mainWorkArea.add(uasujp);
        cardLayout.next(this.mainWorkArea);
    }//GEN-LAST:event_btnSignUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

}
