/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.Profiles.EmployeeProfile;
import Business.Profiles.Profile;
import Business.UserAccounts.UserAccount;
import javax.swing.JPanel;

/**
 *h
 * @author kal bugrara
 */

public class AdminUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    UserAccount selecteduseraccount;
    Business business;

    public AdminUserAccount(UserAccount sua, JPanel jp, Business b) {

        CardSequencePanel = jp;
        selecteduseraccount= sua;
        this.business = b;
        initComponents();
        
        // Setting Name and role
       
        fieldN.setText(selecteduseraccount.getPersonId());
        comboxRole.setSelectedItem(selecteduseraccount.getRole());


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Back1 = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        comboxRole = new javax.swing.JComboBox<>();
        lblN = new javax.swing.JLabel();
        fieldN = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblUpdate.setText("Update>>");
        lblUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblUpdateActionPerformed(evt);
            }
        });
        add(lblUpdate);
        lblUpdate.setBounds(480, 290, 100, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Administer User Account");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        Back1.setText("<< Back");
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        add(Back1);
        Back1.setBounds(40, 290, 100, 23);

        lblRole.setText("Role");
        add(lblRole);
        lblRole.setBounds(190, 150, 120, 16);

        comboxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Faculty", "Student" }));
        comboxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxRoleActionPerformed(evt);
            }
        });
        add(comboxRole);
        comboxRole.setBounds(300, 150, 160, 22);

        lblN.setText("Name");
        add(lblN);
        lblN.setBounds(190, 110, 80, 16);

        fieldN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNActionPerformed(evt);
            }
        });
        add(fieldN);
        fieldN.setBounds(300, 110, 160, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void lblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblUpdateActionPerformed
        // TODO add your handling code here:

        // Adding as a faculty or admin based on combo box selected role
        Profile profile = null;
        
        if (((comboxRole.getSelectedItem()).toString()).equals("Admin")){
            profile = business.getEmployeeDirectory().newEmployeeProfile(selecteduseraccount.getAssociatedPersonProfile().getPerson());
        }
        else if(((comboxRole.getSelectedItem()).toString()).equals("Faculty")){
            profile = business.getFacultyDirectory().newFacultyProfile(selecteduseraccount.getAssociatedPersonProfile().getPerson());
        }
        
        selecteduseraccount.setProfile(profile);
        
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);  

    }//GEN-LAST:event_lblUpdateActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_Back1ActionPerformed

    private void comboxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxRoleActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_comboxRoleActionPerformed

    private void fieldNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back1;
    private javax.swing.JComboBox<String> comboxRole;
    private javax.swing.JTextField fieldN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblRole;
    private javax.swing.JButton lblUpdate;
    // End of variables declaration//GEN-END:variables

}
