/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author gagan
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Product product;
    public CreateJPanel(Product p) {
        initComponents();
        product = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fieldDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldAvailability = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldPrice = new javax.swing.JTextField();
        lblManu = new javax.swing.JLabel();
        lblShipping = new javax.swing.JLabel();
        lblManuStreet = new javax.swing.JLabel();
        lblManuUnit = new javax.swing.JLabel();
        lblManuCity = new javax.swing.JLabel();
        lblManuZipcode = new javax.swing.JLabel();
        fieldManuStreet = new javax.swing.JTextField();
        fieldManuUnit = new javax.swing.JTextField();
        fieldManuCity = new javax.swing.JTextField();
        fieldManuZipcode = new javax.swing.JTextField();
        lblShippingStreet = new javax.swing.JLabel();
        lblShippingUnit = new javax.swing.JLabel();
        lblShippingCity = new javax.swing.JLabel();
        lblShippingZipcode = new javax.swing.JLabel();
        fieldShippingStreet = new javax.swing.JTextField();
        fieldShippingUnit = new javax.swing.JTextField();
        fieldShippingCity = new javax.swing.JTextField();
        fieldShippingZipcode = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Create a Product");

        lblName.setText("Name");

        jLabel1.setText("Description");

        jLabel2.setText("Availability");

        jLabel3.setText("Price");

        fieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPriceActionPerformed(evt);
            }
        });

        lblManu.setText("Manufacture Address");

        lblShipping.setText("Shipping Address");

        lblManuStreet.setText("Street Name");

        lblManuUnit.setText("Unit Number");

        lblManuCity.setText("City");

        lblManuZipcode.setText("Zip Code");

        fieldManuStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManuStreetActionPerformed(evt);
            }
        });

        lblShippingStreet.setText("Street Name");

        lblShippingUnit.setText("Unit Number");

        lblShippingCity.setText("City");

        lblShippingZipcode.setText("Zip Code");

        fieldShippingStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingStreetActionPerformed(evt);
            }
        });

        fieldShippingUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingUnitActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblManuStreet)
                            .addComponent(lblManuUnit)
                            .addComponent(lblManuCity)
                            .addComponent(lblManuZipcode))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldManuZipcode, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(fieldManuCity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldManuUnit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldManuStreet, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblShippingStreet)
                                .addGap(18, 18, 18)
                                .addComponent(fieldShippingStreet))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblShippingUnit)
                                .addGap(18, 18, 18)
                                .addComponent(fieldShippingUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblShippingZipcode)
                                    .addComponent(lblShippingCity))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldShippingZipcode, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(fieldShippingCity))))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(lblName)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldDescription)
                            .addComponent(fieldName)
                            .addComponent(fieldAvailability)
                            .addComponent(fieldPrice)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(193, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblManu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblShipping, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManu)
                    .addComponent(lblShipping))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManuStreet)
                    .addComponent(fieldManuStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShippingStreet)
                    .addComponent(fieldShippingStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManuUnit)
                    .addComponent(fieldManuUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShippingUnit)
                    .addComponent(fieldShippingUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManuCity)
                    .addComponent(fieldManuCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShippingCity)
                    .addComponent(fieldShippingCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManuZipcode)
                    .addComponent(fieldManuZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShippingZipcode)
                    .addComponent(fieldShippingZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPriceActionPerformed

    private void fieldManuStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManuStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManuStreetActionPerformed

    private void fieldShippingStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingStreetActionPerformed

    private void fieldShippingUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingUnitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        // Step 1: Collect text from the field
        String name = fieldName.getText();
        String description = fieldDescription.getText();
        String avail = fieldAvailability.getText();
        String price = fieldPrice.getText();
        
        String manuStreet = fieldManuStreet.getText();
        String manuUnit = fieldManuUnit.getText();
        String manuCity =  fieldManuCity.getText();
        String manuZip = fieldManuZipcode.getText();
        
        String shippingStreet = fieldShippingStreet.getText();
        String shippingUnit = fieldShippingUnit.getText();
        String shippingCity = fieldShippingCity.getText();
        String shippingZip = fieldShippingZipcode.getText();
        
        //Step 2: put those information to product
        
        product.setName(name);
        product.setDescription(description);
        product.setAvailNum(avail);
        product.setPrice(price);
        
        product.getManufactureAddress().setStreetName(manuStreet);
        product.getManufactureAddress().setUnitNum(manuUnit);
        product.getManufactureAddress().setCity(manuCity);
        product.getManufactureAddress().setZipcode(manuZip);
        
        product.getShippingAddress().setStreetName(shippingStreet);
        product.getShippingAddress().setUnitNum(shippingUnit);
        product.getShippingAddress().setCity(shippingCity);
        product.getShippingAddress().setZipcode(shippingZip);
        
        
        // Step 3: Set a little pop-up message
        JOptionPane.showMessageDialog(this, "Successfully saved");
        
        // Step 4: clear all textfield
        
        fieldName.setText("");
        fieldDescription.setText("");
        fieldAvailability.setText("");
        fieldPrice.setText("");
        fieldManuStreet.setText("");
        fieldManuUnit.setText("");
        fieldManuCity.setText("");
        fieldManuZipcode.setText("");
        fieldShippingStreet.setText("");
        fieldShippingUnit.setText("");
        fieldShippingCity.setText("");
        fieldShippingZipcode.setText("");
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAvailability;
    private javax.swing.JTextField fieldDescription;
    private javax.swing.JTextField fieldManuCity;
    private javax.swing.JTextField fieldManuStreet;
    private javax.swing.JTextField fieldManuUnit;
    private javax.swing.JTextField fieldManuZipcode;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField fieldShippingCity;
    private javax.swing.JTextField fieldShippingStreet;
    private javax.swing.JTextField fieldShippingUnit;
    private javax.swing.JTextField fieldShippingZipcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblManu;
    private javax.swing.JLabel lblManuCity;
    private javax.swing.JLabel lblManuStreet;
    private javax.swing.JLabel lblManuUnit;
    private javax.swing.JLabel lblManuZipcode;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblShipping;
    private javax.swing.JLabel lblShippingCity;
    private javax.swing.JLabel lblShippingStreet;
    private javax.swing.JLabel lblShippingUnit;
    private javax.swing.JLabel lblShippingZipcode;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
