/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gagan
 */
public class AddCustomerOrderJPanel extends javax.swing.JPanel {

    /**-
     * 
     * Creates new form AddCustomerOrderJPanel
     */
    private ArrayList<Product> p;
    private ArrayList<Customer> c;
    
    Customer customer;
    JPanel mainWorkArea;
    
    public AddCustomerOrderJPanel(ArrayList<Product> product,ArrayList<Customer> customer, JPanel mainWorkArea  ) {
        initComponents();
        
        this.p = product;
        this.c = customer;
        this.mainWorkArea = mainWorkArea;
        
        this.customer = new Customer();
        fieldCusID.setText(String.valueOf(this.customer.getCustomerID()));
        fieldOrdID.setText(String.valueOf(this.customer.getOrder().getOrderID()));
        
        this.c.add(this.customer);
        
        populateProductOpted();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddCusOrd = new javax.swing.JLabel();
        lblCusID = new javax.swing.JLabel();
        fieldCusID = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        fieldContact = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblOrdID = new javax.swing.JLabel();
        lblOrdDate = new javax.swing.JLabel();
        lblOrdTime = new javax.swing.JLabel();
        lblOrdType = new javax.swing.JLabel();
        lblPaymentMethod = new javax.swing.JLabel();
        lblOrdStatus = new javax.swing.JLabel();
        lblPrdOpt = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        fieldOrdID = new javax.swing.JTextField();
        fieldOrdDate = new javax.swing.JTextField();
        fieldOrdTime = new javax.swing.JTextField();
        fieldQty = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        comboxOrdType = new javax.swing.JComboBox<>();
        comboxPaymentMethod = new javax.swing.JComboBox<>();
        comboxOrdStatus = new javax.swing.JComboBox<>();
        comboxPrdOpt = new javax.swing.JComboBox<>();

        lblAddCusOrd.setText("Add Customer and Order details");

        lblCusID.setText("Customer ID");

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblContact.setText("Contact");

        lblOrdID.setText("Order ID");

        lblOrdDate.setText("Order Date");

        lblOrdTime.setText("Order Time");

        lblOrdType.setText("Order Type");

        lblPaymentMethod.setText("Payment Method");

        lblOrdStatus.setText("Order Status");

        lblPrdOpt.setText("Product Opted");

        lblQty.setText("Number (Qty)");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        comboxOrdType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dine-In", "Takeout", "Pickup", " " }));
        comboxOrdType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxOrdTypeActionPerformed(evt);
            }
        });

        comboxPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Mobile", " " }));

        comboxOrdStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Preparing", "Ready", "Completed" }));

        comboxPrdOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxPrdOptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddCusOrd)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCusID)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblLastName)
                                    .addComponent(lblContact)
                                    .addComponent(lblOrdID)
                                    .addComponent(lblOrdDate)
                                    .addComponent(lblOrdTime)
                                    .addComponent(lblOrdType)
                                    .addComponent(lblPaymentMethod)
                                    .addComponent(lblOrdStatus)
                                    .addComponent(lblPrdOpt)
                                    .addComponent(lblQty))
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldCusID)
                                    .addComponent(fieldFirstName)
                                    .addComponent(fieldLastName)
                                    .addComponent(fieldContact)
                                    .addComponent(fieldOrdID)
                                    .addComponent(fieldOrdDate)
                                    .addComponent(fieldOrdTime)
                                    .addComponent(comboxOrdType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboxPaymentMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboxOrdStatus, 0, 144, Short.MAX_VALUE)
                                    .addComponent(comboxPrdOpt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldQty)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddCusOrd)
                        .addGap(18, 18, 18)
                        .addComponent(lblCusID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContact)
                    .addComponent(fieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrdID)
                    .addComponent(fieldOrdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrdDate)
                    .addComponent(fieldOrdDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrdTime)
                    .addComponent(fieldOrdTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrdType)
                    .addComponent(comboxOrdType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaymentMethod)
                    .addComponent(comboxPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrdStatus)
                    .addComponent(comboxOrdStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrdOpt)
                    .addComponent(comboxPrdOpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQty)
                    .addComponent(fieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnReset))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        
        String customerID = fieldCusID.getText();
        String firstName = fieldFirstName.getText();
        String lastName = fieldLastName.getText();
        String contact = fieldContact.getText();
        String date = fieldOrdDate.getText();
        String time = fieldOrdTime.getText();
        String number = fieldQty.getText();
        String orderStatus = comboxOrdStatus.getSelectedItem().toString();
        String orderType = comboxOrdType.getSelectedItem().toString();
        String paymentMethod = comboxPaymentMethod.getSelectedItem().toString();
        String orderID = fieldOrdID.getText();
        
        
        if(customerID.isBlank()||orderID.isBlank()||firstName.isBlank()|| lastName.isBlank()||contact.isBlank() || date.isBlank()||time.isBlank()|| number.isBlank()){
            JOptionPane.showMessageDialog(this, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Product selectedProduct = (Product) comboxPrdOpt.getSelectedItem();
        
        customer.getOrder().setProduct(selectedProduct);
        customer.setCustomerID(Long.parseLong(customerID));
        customer.getOrder().setOrderID(Integer.parseInt(orderID));
        customer.setFirstName(firstName);
        customer.setLastName(lastName);
        customer.setContact(contact);
        customer.getOrder().setDateTime(date);
        selectedProduct.setNumber(Integer.parseInt(number));
        customer.getOrder().setOrderStatus(orderStatus);
        customer.getOrder().setOrdertType(orderType);
        customer.getOrder().setPaymentMethod(paymentMethod);
        
        JOptionPane.showMessageDialog(this, "Successfully Saved", "Information", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        fieldCusID.setText("");
        fieldFirstName.setText("");
        fieldLastName.setText("");
        fieldContact.setText("");
        fieldOrdID.setText("");
        fieldOrdDate.setText("");
        fieldOrdTime.setText("");
        comboxOrdType.setSelectedIndex(0);
        comboxPaymentMethod.setSelectedIndex(0);
        comboxOrdStatus.setSelectedIndex(0);
        comboxPrdOpt.setSelectedIndex(0);
        fieldQty.setText("");


    }//GEN-LAST:event_btnResetActionPerformed

    private void comboxOrdTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxOrdTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxOrdTypeActionPerformed

    private void comboxPrdOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxPrdOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxPrdOptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboxOrdStatus;
    private javax.swing.JComboBox<String> comboxOrdType;
    private javax.swing.JComboBox<String> comboxPaymentMethod;
    private javax.swing.JComboBox<Product> comboxPrdOpt;
    private javax.swing.JTextField fieldContact;
    private javax.swing.JTextField fieldCusID;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldOrdDate;
    private javax.swing.JTextField fieldOrdID;
    private javax.swing.JTextField fieldOrdTime;
    private javax.swing.JTextField fieldQty;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddCusOrd;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCusID;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblOrdDate;
    private javax.swing.JLabel lblOrdID;
    private javax.swing.JLabel lblOrdStatus;
    private javax.swing.JLabel lblOrdTime;
    private javax.swing.JLabel lblOrdType;
    private javax.swing.JLabel lblPaymentMethod;
    private javax.swing.JLabel lblPrdOpt;
    private javax.swing.JLabel lblQty;
    // End of variables declaration//GEN-END:variables

    private void populateProductOpted() {
        
        comboxPrdOpt.removeAllItems();
         
        for (Product product : p){
            comboxPrdOpt.addItem(product);
         }
    }
    
}
