/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gagan
 */
public class ListOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListOrdersJPanel
     */
    JPanel mainWorkArea;
    ArrayList<Customer> customers;
    Customer selectedCustomer = null;
    
    public ListOrdersJPanel(JPanel mainWorkArea, ArrayList<Customer> customers) {
        initComponents();
        
        this.mainWorkArea = mainWorkArea;
        this.customers = customers;

        initComponents();

        this.mainWorkArea = mainWorkArea;
        this.customers = customers;

        // Initialize the table with all orders
        populateOrdersTable();

    }

    private void populateOrdersTable() {
        DefaultTableModel model = (DefaultTableModel) tblListOrders.getModel();
        model.setRowCount(0);

        for (Customer customer : customers) {
            Object[] row = new Object[4];
            row[0] = customer.getCustomerID();
            row[1] = customer.getOrder().getOrderID();
            row[2] = customer.getOrder().getProduct().getName(); // Product name instead of object
            row[3] = customer.getOrder().getProduct().getPrice();

            model.addRow(row);
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListOrders = new javax.swing.JTable();
        lblCusID = new javax.swing.JLabel();
        fieldCusID = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblOrderID = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        fieldOrderID = new javax.swing.JTextField();
        fieldProduct = new javax.swing.JTextField();
        fieldPrice = new javax.swing.JTextField();

        tblListOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Order ID", "Product", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListOrders);

        lblCusID.setText("Customer ID");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblOrderID.setText("Order ID");

        lblProduct.setText("Product");

        lblPrice.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(btnView))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrderID)
                                    .addComponent(lblCusID)
                                    .addComponent(lblProduct)
                                    .addComponent(lblPrice))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDelete)
                            .addComponent(fieldCusID)
                            .addComponent(fieldOrderID)
                            .addComponent(fieldProduct)
                            .addComponent(fieldPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnDelete))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCusID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrderID)
                    .addComponent(fieldOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduct)
                    .addComponent(fieldProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
    int selectedRow = tblListOrders.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get customer ID from selected row and find the customer
    long customerID = (Long) tblListOrders.getValueAt(selectedRow, 0);
    
    for (Customer customer : customers) {
        if (customer.getCustomerID() == customerID) {
            selectedCustomer = customer;
            break;
        }
    }
    
    if (selectedCustomer != null) {
        // Populate form fields
        fieldCusID.setText(String.valueOf(selectedCustomer.getCustomerID()));
        fieldOrderID.setText(String.valueOf(selectedCustomer.getOrder().getOrderID()));
        fieldProduct.setText(selectedCustomer.getOrder().getProduct().getName());
        fieldPrice.setText(String.valueOf(selectedCustomer.getOrder().getProduct().getPrice()));
    }

    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblListOrders.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get customer ID from selected row
        long customerID = (Long) tblListOrders.getValueAt(selectedRow, 0);

        // Find and remove the customer from the list
        Customer customerToRemove = null;
        for (Customer customer : customers) {
            if (customer.getCustomerID() == customerID) {
                customerToRemove = customer;
                break;
            }
        }

        if (customerToRemove != null) {
            customers.remove(customerToRemove);
        }
       
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField fieldCusID;
    private javax.swing.JTextField fieldOrderID;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField fieldProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCusID;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JTable tblListOrders;
    // End of variables declaration//GEN-END:variables
}

