/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Customer;
import Model.Product;
import java.awt.CardLayout;
import java.util.ArrayList;

/**
 *
 * @author gagan
 */

public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    ArrayList<Customer> customerlist;
    ArrayList<Product> productlist;
    Customer c;
    
    
    public MainJFrame() {
        initComponents();
        this.customerlist = new ArrayList<Customer>();
        this.productlist = new ArrayList<Product>();
        
        Product p1 = new Product();
        Product p2 = new Product();
        Product p3 = new Product();
        Product p4 = new Product();
        Product p5 = new Product();

        
        p1.setName("BlackCoffee");
        p1.setCategory("Coffee");
        p1.setNumber(2);
        p1.setPreparationTime("45");
        p1.setPrice(22f);
        p1.setProductID(1);

        
                
        p2.setName("Cappa");
        p2.setCategory("Coffee");
        p2.setNumber(1);
        p2.setPreparationTime("30");
        p2.setPrice(12f);
        p2.setProductID(2);

        
        
                
        p3.setName("Cappucchino");
        p3.setCategory("Coffee");
        p3.setNumber(5);
        p3.setPreparationTime("60");
        p3.setPrice(102f);
        p3.setProductID(3);

        
        
                
        p4.setName("GrenTea");
        p4.setCategory("Tea");
        p4.setNumber(1);
        p4.setPreparationTime("10");
        p4.setPrice(2f);
        p4.setProductID(4);

        
                
        p5.setName("VegSandwich");
        p5.setCategory("Sandwich");
        p5.setNumber(10);
        p5.setPreparationTime("120");
        p5.setPrice(120f);
        p5.setProductID(5);

        
        
        this.productlist.add(p1);
        this.productlist.add(p2);
        this.productlist.add(p3);
        this.productlist.add(p4);
        this.productlist.add(p5);

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnMngProd = new javax.swing.JButton();
        btnSearchCus = new javax.swing.JButton();
        btnListOrd = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        title.setText("Coffee POS");

        btnAdd.setText("Add Customer+Order");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMngProd.setText("Manage Products");
        btnMngProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngProdActionPerformed(evt);
            }
        });

        btnSearchCus.setText("Search Customers");
        btnSearchCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCusActionPerformed(evt);
            }
        });

        btnListOrd.setText("List Orders");
        btnListOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListOrdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMngProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearchCus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(title)
                .addGap(65, 65, 65)
                .addComponent(btnAdd)
                .addGap(27, 27, 27)
                .addComponent(btnMngProd)
                .addGap(28, 28, 28)
                .addComponent(btnSearchCus)
                .addGap(27, 27, 27)
                .addComponent(btnListOrd)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        AddCustomerOrderJPanel addCustomerOrderJPanel = new AddCustomerOrderJPanel(productlist, customerlist, this.workArea);
        splitPane.setRightComponent(addCustomerOrderJPanel);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMngProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngProdActionPerformed
        // TODO add your handling code here:
        
        ManageProductJPanel manageProductJPanel = new ManageProductJPanel( productlist, this.workArea);
        splitPane.setRightComponent(manageProductJPanel);
    }//GEN-LAST:event_btnMngProdActionPerformed

    private void btnSearchCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCusActionPerformed
            // TODO add your handling code here:
        SearchCustomerJPanel searchCustomerJPanel = new SearchCustomerJPanel( this.workArea, this.customerlist, this.c);
        splitPane.setRightComponent(searchCustomerJPanel);
    }//GEN-LAST:event_btnSearchCusActionPerformed

    private void btnListOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListOrdActionPerformed
        // TODO add your handling code here:
        ListOrdersJPanel listOrdersJPanel = new ListOrdersJPanel( this.workArea, this.customerlist);
        splitPane.setRightComponent(listOrdersJPanel);
        
//        ListOrdersJPanel lo = new ListOrdersJPanel( this.workArea, this.customers);
//        workArea.add("SearchCustomerJPanel", lo);
//        CardLayout layout = (CardLayout) workArea.getLayout();
//        layout.next(workArea);
        
    }//GEN-LAST:event_btnListOrdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnListOrd;
    private javax.swing.JButton btnMngProd;
    private javax.swing.JButton btnSearchCus;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel title;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
