/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gagan
 */
public class ManageProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageProductJPanel
     */
    JPanel mainWorkArea;
    ArrayList<Product> product;

    public ManageProductJPanel(ArrayList<Product> product, JPanel mainWorkArea) {
        initComponents();
        
        this.mainWorkArea = mainWorkArea;
        this.product = product;
         btnUpdate.setEnabled(false);
        populateTable();
 

    }
    
    
    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblPrd.getModel();
        model.setRowCount(0);
        
        for (Product p : this.product) {
            
            Object[] row = new Object[6];
            row[0] = p.getProductID();
            row[1] = p.getName();
            row[2] = p.getCategory();
            row[3] = p.getPrice();
            row[4] = p.getNumber();
            row[5] = p.getPreparationTime();
            
            
            model.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProdID = new javax.swing.JLabel();
        lblProdName = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblPreTime = new javax.swing.JLabel();
        fieldProdID = new javax.swing.JTextField();
        fieldProdName = new javax.swing.JTextField();
        fieldPrice = new javax.swing.JTextField();
        fieldNumber = new javax.swing.JTextField();
        fieldPreTime = new javax.swing.JTextField();
        comboxCategory = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrd = new javax.swing.JTable();
        btnView = new javax.swing.JButton();

        lblProdID.setText("Product ID");

        lblProdName.setText("Product Name");

        lblCategory.setText("category");

        lblPrice.setText("Price");

        lblNumber.setText("Number");

        lblPreTime.setText("Preparation time (minutes)");

        fieldProdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldProdNameActionPerformed(evt);
            }
        });

        comboxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coffee", "Tea", "Pastry", "Sandwich" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tblPrd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Price", "Number", "Prep Time"
            }
        ));
        jScrollPane1.setViewportView(tblPrd);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblProdName)
                                .addComponent(lblProdID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCategory, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblNumber)
                            .addComponent(lblPreTime))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldProdID)
                            .addComponent(fieldProdName)
                            .addComponent(fieldPrice)
                            .addComponent(fieldNumber)
                            .addComponent(fieldPreTime)
                            .addComponent(comboxCategory, 0, 170, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnAdd)
                        .addGap(55, 55, 55)
                        .addComponent(btnUpdate)
                        .addGap(29, 29, 29)
                        .addComponent(btnView)
                        .addGap(30, 30, 30)
                        .addComponent(btnDelete)
                        .addGap(48, 48, 48)
                        .addComponent(btnClear)))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdID)
                    .addComponent(fieldProdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdName)
                    .addComponent(fieldProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(comboxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber)
                    .addComponent(fieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreTime)
                    .addComponent(fieldPreTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnView))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldProdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldProdNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        Product p = new Product();
        
        p.setProductID(Integer.parseInt(fieldProdID.getText()));
        p.setCategory(comboxCategory.getSelectedItem().toString());
        p.setName(fieldProdName.getText());
        p.setPrice(Double.parseDouble(fieldPrice.getText()));
        p.setNumber(Integer.parseInt(fieldNumber.getText()));
        p.setPreparationTime(fieldPreTime.getText());
        
        
        product.add(p);
        populateTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int row = tblPrd.getSelectedRow();
        if (row < 0){
            JOptionPane.showMessageDialog(null,"Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int productID = (Integer)tblPrd.getValueAt(row, 0);
        Product rowDetails = null;

        // Find the product with matching ID
        for (Product p : this.product) {
            if (p.getProductID() == productID) {
                rowDetails = p;
                break;
            }
        }
       if (rowDetails != null) {

        fieldNumber.setText(String.valueOf(rowDetails.getNumber()));
        fieldPreTime.setText(rowDetails.getPreparationTime());
        fieldPrice.setText(String.valueOf(rowDetails.getPrice()));
        fieldProdName.setText(rowDetails.getName());
        fieldProdID.setText(String.valueOf(rowDetails.getProductID()));
        comboxCategory.setSelectedItem(rowDetails.getCategory());
        
        btnDelete.setEnabled(false);
        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(true);
       }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = tblPrd.getSelectedRow();
        
        int productID = (Integer)tblPrd.getValueAt(row, 0);
        Product rowDetails = null;

        // Find the product with matching ID
        for (Product p : this.product) {
            if (p.getProductID() == productID) {
                rowDetails = p;
                break;
            }
        }

        if (rowDetails != null) {        
        rowDetails.setNumber(Integer.parseInt(fieldNumber.getText()));
        rowDetails.setPreparationTime(fieldPreTime.getText());
        rowDetails.setPrice(Double.parseDouble(fieldPrice.getText()));
        rowDetails.setName(fieldProdName.getText());
        rowDetails.setProductID(Integer.parseInt(fieldProdID.getText()));
        rowDetails.setCategory(comboxCategory.getSelectedItem().toString());
        
        btnDelete.setEnabled(true);
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(false);
        
        populateTable();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        fieldNumber.setText("");
        fieldPreTime.setText("");
        fieldPrice.setText("");
        fieldProdName.setText("");
        fieldProdID.setText("");
        comboxCategory.setSelectedItem("");
        btnDelete.setEnabled(true);
        btnAdd.setEnabled(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblPrd.getSelectedRow();
        if (row < 0){
            JOptionPane.showMessageDialog(null,"Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int productID = (Integer)tblPrd.getValueAt(row, 0);
        Product rowDetails = null;

        // Find the product with matching ID
        for (Product p : this.product) {
            if (p.getProductID() == productID) {
                rowDetails = p;
                break;
            }
        }

        if (rowDetails != null) {
            this.product.remove(rowDetails);
            populateTable();
        }

    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> comboxCategory;
    private javax.swing.JTextField fieldNumber;
    private javax.swing.JTextField fieldPreTime;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField fieldProdID;
    private javax.swing.JTextField fieldProdName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPreTime;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProdID;
    private javax.swing.JLabel lblProdName;
    private javax.swing.JTable tblPrd;
    // End of variables declaration//GEN-END:variables


    
    }

