/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.Product;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gagan
 */
public class SearchCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchCustomerJPanel
     */
    
    JPanel mainWorkArea;
    ArrayList<Customer> searchResults;
    ArrayList<Customer> customers;
    Customer c;

    

    public SearchCustomerJPanel(JPanel mainWorkArea, ArrayList<Customer> customers, Customer c) {
        initComponents();
        
        this.mainWorkArea = mainWorkArea;
        this.searchResults = new ArrayList<>(customers);
        this.customers = customers;
        this.c = c;
        
        
        this.populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearchCusID = new javax.swing.JLabel();
        fieldSearchCusID = new javax.swing.JTextField();
        btnSearchID = new javax.swing.JButton();
        lblSearchName = new javax.swing.JLabel();
        fieldSearchName = new javax.swing.JTextField();
        btnSearchName = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        btnUpdateCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        lblCusID = new javax.swing.JLabel();
        fieldCusID = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        fieldContact = new javax.swing.JTextField();
        lblOrdID = new javax.swing.JLabel();
        fieldOrdID = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        fieldStatus = new javax.swing.JTextField();
        lblQty = new javax.swing.JLabel();
        fieldQty = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        lblSearchCusID.setText("Search by Customer ID");

        fieldSearchCusID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSearchCusIDActionPerformed(evt);
            }
        });

        btnSearchID.setText("Search ID");
        btnSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIDActionPerformed(evt);
            }
        });

        lblSearchName.setText("Search by Name");

        btnSearchName.setText("Search Name");
        btnSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNameActionPerformed(evt);
            }
        });

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "First Name", "Last Name", "Contact", "Order ID", "DateTime", "Status", "Items (Qty)"
            }
        ));
        jScrollPane1.setViewportView(tblSearch);

        btnUpdateCustomer.setText("Update Customer");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        btnDeleteCustomer.setText("Delete Customer");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblCusID.setText("Customer ID");

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblContact.setText("Contact");

        lblOrdID.setText("Order ID");

        fieldOrdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOrdIDActionPerformed(evt);
            }
        });

        lblDate.setText("DateTime");

        lblStatus.setText("Status");

        lblQty.setText("Item (Qty)");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSearchCusID)
                            .addComponent(lblSearchName))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldSearchCusID)
                            .addComponent(fieldSearchName, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearchID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearchName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFirstName)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblContact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(lblOrdID)
                                            .addComponent(lblDate)
                                            .addComponent(lblQty))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCusID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                        .addComponent(fieldCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(btnUpdateCustomer)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldQty)
                                            .addComponent(fieldStatus)
                                            .addComponent(fieldDate)
                                            .addComponent(fieldOrdID)
                                            .addComponent(fieldContact)
                                            .addComponent(fieldLastName)
                                            .addComponent(fieldFirstName)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(btnView)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSave)))))
                        .addGap(46, 46, 46)
                        .addComponent(btnDeleteCustomer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchCusID)
                    .addComponent(fieldSearchCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchName)
                    .addComponent(fieldSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateCustomer)
                    .addComponent(btnView)
                    .addComponent(btnDeleteCustomer)
                    .addComponent(btnSave))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusID)
                    .addComponent(fieldCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContact)
                    .addComponent(fieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrdID)
                    .addComponent(fieldOrdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(fieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(fieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQty)
                    .addComponent(fieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldSearchCusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSearchCusIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSearchCusIDActionPerformed

    private void btnSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIDActionPerformed
        long searchId = Long.parseLong(fieldSearchCusID.getText());
        this.searchResults = new ArrayList<>();
        
        this.customers.forEach((customer) ->{
            if(customer.getCustomerID() == searchId) {
                this.searchResults.add(customer);
            }
        } );
        populateTable();
    }//GEN-LAST:event_btnSearchIDActionPerformed

    private void btnSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNameActionPerformed
        // TODO add your handling code here:
        String searchName = fieldSearchName.getText();
        this.searchResults = new ArrayList<>();
        
        this.customers.forEach((customer) ->{
            if(customer.getFirstName().startsWith(searchName)) {
                this.searchResults.add(customer);
            }
        } );
        populateTable();
    }//GEN-LAST:event_btnSearchNameActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int row = tblSearch.getSelectedRow();
        if (row < 0){
            JOptionPane.showMessageDialog(null,"Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
//        
//        Customer customerDetails = (Customer)tblSearch.getValueAt(row,0);
//        
//        ViewCustomerJPanel panel = new ViewCustomerJPanel(mainWorkArea, customerDetails);
//        mainWorkArea.add("ViewCustomerJPanel", panel);
//        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
//        layout.next(mainWorkArea);

        int selectedRow = tblSearch.getSelectedRow();
        
        if (selectedRow>=0 ){
           Customer selectedCustomer = (Customer) tblSearch.getValueAt(selectedRow, 0);
           
        fieldCusID.setText(String.valueOf(selectedCustomer.getCustomerID()));
        fieldFirstName.setText(selectedCustomer.getFirstName());
        fieldLastName.setText(selectedCustomer.getLastName());
        fieldContact.setText(selectedCustomer.getContact());
        fieldOrdID.setText(String.valueOf(selectedCustomer.getOrder().getOrderID()));
        fieldDate.setText(selectedCustomer.getOrder().getDateTime());
        fieldStatus.setText(selectedCustomer.getOrder().getOrderStatus());
        fieldQty.setText(String.valueOf(selectedCustomer.getOrder().getProduct().getNumber()));
        
        btnDeleteCustomer.setEnabled(false);
        btnSave.setEnabled(false);
        fieldCusID.setEditable(false);
        fieldFirstName.setEditable(false);
        fieldLastName.setEditable(false);
        fieldContact.setEditable(false);
        fieldOrdID.setEditable(false);
        fieldDate.setEditable(false);
        fieldStatus.setEditable(false);
        fieldQty.setEditable(false);

        }   
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void fieldOrdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOrdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOrdIDActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:
        
        btnDeleteCustomer.setEnabled(false);
        btnView.setEnabled(false);
        btnSave.setEnabled(true);
        fieldCusID.setEditable(true);
        fieldFirstName.setEditable(true);
        fieldLastName.setEditable(true);
        fieldContact.setEditable(true);
        fieldOrdID.setEditable(true);
        fieldDate.setEditable(true);
        fieldStatus.setEditable(true);
        fieldQty.setEditable(true);
    }//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        c.setCustomerID(Long.parseLong(fieldCusID.getText()));
        c.setFirstName(fieldFirstName.getText());
        c.setLastName(fieldLastName.getText());
        c.setContact(fieldContact.getText());
        c.getOrder().setOrderID(Integer.parseInt(fieldOrdID.getText()));
        c.getOrder().setDateTime(fieldDate.getText());
        c.getOrder().setOrderStatus(fieldStatus.getText());
        c.getOrder().getProduct().setNumber(Integer.parseInt(fieldQty.getText()));
        
        
        JOptionPane.showMessageDialog(this, "Saved Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
        populateTable();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchID;
    private javax.swing.JButton btnSearchName;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField fieldContact;
    private javax.swing.JTextField fieldCusID;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldOrdID;
    private javax.swing.JTextField fieldQty;
    private javax.swing.JTextField fieldSearchCusID;
    private javax.swing.JTextField fieldSearchName;
    private javax.swing.JTextField fieldStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCusID;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblOrdID;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblSearchCusID;
    private javax.swing.JLabel lblSearchName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblSearch;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
       DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
       model.setRowCount(0);
        
        for (Customer c : this.searchResults) {
            
            Object[] row = new Object[8];
            row[0] = c.getCustomerID();
            row[1] = c.getFirstName();
            row[2] = c.getLastName();
            row[3] = c.getContact();
            row[4] = c.getOrder().getOrderID();
            row[5] = c.getOrder().getDateTime();
            row[6] = c.getOrder().getOrderStatus();
            row[7] = c.getOrder().getProduct().getNumber();
            
            
            model.addRow(row);
        }
    }
}
