/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import Library.Branches.Branch;
import Library.Branches.BranchDirectory;
import Library.Person.Person;
import Library.Profiles.BranchManagerProfile;
import Library.Profiles.Profile;
import Library.UserAccounts.UserAccountDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author gagan
 */
public class EmployeesJPanel extends javax.swing.JPanel {
    
    private UserAccountDirectory userDir;
    private BranchDirectory branchDir;
    private Branch selectedBranch;

    /**
     * Creates new form EmployeesJPanel
     */
    public EmployeesJPanel(UserAccountDirectory userDir, BranchDirectory branchDir) {
        initComponents();
        this.userDir = userDir;
        this.branchDir = branchDir;
        this.selectedBranch = null;
        
        comboxBranch.removeAllItems();
        for (Branch branch : branchDir.getBranchlist()) {
        comboxBranch.addItem(branch);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBranch = new javax.swing.JLabel();
        comboxBranch = new javax.swing.JComboBox<>();
        lblName = new javax.swing.JLabel();
        lblExperience = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtExperience = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        btnAccount = new javax.swing.JButton();

        lblBranch.setText("Branch");

        comboxBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxBranchActionPerformed(evt);
            }
        });

        lblName.setText("Name");

        lblExperience.setText("Experience");

        lblUserName.setText("Username");

        lblPass.setText("Password");

        btnAccount.setText("Assign Manager + Account");
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblExperience, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboxBranch, 0, 201, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addComponent(txtExperience)
                    .addComponent(txtUserName)
                    .addComponent(txtPass))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAccount)
                .addGap(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBranch)
                    .addComponent(comboxBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExperience)
                    .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(btnAccount)
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        // TODO add your handling code here:
        
        String name = txtName.getText();
        String un = txtUserName.getText();
        String pass = txtPass.getText();
        int exp = Integer.parseInt(txtExperience.getText());
        
        Branch b = (Branch) comboxBranch.getSelectedItem();
        
        Profile profile = new BranchManagerProfile(new Person(name), exp);
        
        userDir.newUserAccount(profile, un, pass);
        
        this.selectedBranch.setManager(profile);
        
        txtName.setText("");
        txtUserName.setText("");
        txtPass.setText("");
        txtExperience.setText("");
    }//GEN-LAST:event_btnAccountActionPerformed

    private void comboxBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxBranchActionPerformed
        // TODO add your handling code here:
        
        Branch b = (Branch) comboxBranch.getSelectedItem();
        
        if(b == null) {
            JOptionPane.showMessageDialog(this, "Please select a branch");
        } else {
            this.selectedBranch = b;
        }
    }//GEN-LAST:event_comboxBranchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JComboBox<Branch> comboxBranch;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
