/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Customer;

import Library.Book.Book;
import Library.Branches.Branch;
import Library.Branches.BranchDirectory;
import Library.Profiles.CustomerProfile;
import Rental.RentalRecord;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gagan
 */
public class BrowseJPanel extends javax.swing.JPanel {
    
    private BranchDirectory branchDirectory;
    private CustomerProfile customer;
    private Branch selectedBranch;

    /**
     * Creates new form BrowseJPanel
     */
    public BrowseJPanel(BranchDirectory branchDirectory, CustomerProfile customer) {
        initComponents();
        this.branchDirectory = branchDirectory;
        this.customer = customer;
        this.selectedBranch = this.branchDirectory.getBranchlist().get(0);
        this.populateBranches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboxBranch = new javax.swing.JComboBox<>();
        lblBranch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrowse = new javax.swing.JTable();
        btnRentBook = new javax.swing.JButton();

        comboxBranch.setModel(new javax.swing.DefaultComboBoxModel<>());
        comboxBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxBranchActionPerformed(evt);
            }
        });

        lblBranch.setText("Branch :");

        tblBrowse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SN", "Book", "Author", "Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBrowse);

        btnRentBook.setText("Rent Book");
        btnRentBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(comboxBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(btnRentBook)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranch))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRentBook)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboxBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxBranchActionPerformed
        // TODO add your handling code here:
        Branch b = (Branch) this.comboxBranch.getSelectedItem();
        
        if(b == null) {
            return;
        }
        
        this.selectedBranch = b;
        this.refreshTable(b);
    }//GEN-LAST:event_comboxBranchActionPerformed

    private void btnRentBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentBookActionPerformed
        // TODO add your handling code here:
        int row = tblBrowse.getSelectedRow();
        
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Book book = (Book)tblBrowse.getValueAt(row, 1);
        book.setIsRented(true);
        
        RentalRecord record = new RentalRecord(book, customer, this.selectedBranch);
        
        
        this.selectedBranch.getLibrary().getRentalRecordDirectory().addRecord(record);
        this.customer.getRentedBooks().addRecord(record);
        this.refreshTable(this.selectedBranch);
    }//GEN-LAST:event_btnRentBookActionPerformed

    private void populateBranches() {
        this.comboxBranch.removeAll();
        
        for(Branch b: this.branchDirectory.getBranchlist()) {
            this.comboxBranch.addItem(b);
        }
        
        this.refreshTable(this.branchDirectory.getBranchlist().get(0));
    }
    
    private void refreshTable(Branch branch) {
        DefaultTableModel model = (DefaultTableModel)tblBrowse.getModel();
        model.setRowCount(0);
        
        for(Book b: branch.getLibrary().getBookDirectory().getBookList()) {
            Object[] obj = new Object[4];
            obj[0] = b.getsNum();
            obj[1] = b;
            obj[2] = b.getAuthor();
            obj[3] = b.isIsRented() ? "false" : "true";
            model.addRow(obj);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRentBook;
    private javax.swing.JComboBox<Branch> comboxBranch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JTable tblBrowse;
    // End of variables declaration//GEN-END:variables
}
