/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.BranchManager;

import Library.Author.Author;
import Library.Author.AuthorDirectory;
import Library.Book.Book;
import Library.Book.BookDirectory;
import Library.Branches.Branch;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gagan
 */
public class BooksJPanel extends javax.swing.JPanel {
    
    private BookDirectory bookDirectory;
    private AuthorDirectory authorDirectory;
    private Author selectedAuthor;
    
    /**
     * Creates new form BooksJPanel
     */
    public BooksJPanel(BookDirectory bookDirectory, AuthorDirectory authorDirectory) {
        initComponents();
        this.bookDirectory = bookDirectory;
        this.authorDirectory = authorDirectory;
        this.selectedAuthor = null;
        this.populateAuthors();
        this.refreshTable();
    }

    public BookDirectory getBooks() {
        return bookDirectory;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        btnAddBook = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtLang = new javax.swing.JTextField();
        comboxAuthor = new javax.swing.JComboBox<>();
        lblLang = new javax.swing.JLabel();
        lblPages = new javax.swing.JLabel();
        txtPages = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();

        lblName.setText("Name");

        lblAuthor.setText("Author");

        btnAddBook.setText("Add Book");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        comboxAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxAuthorActionPerformed(evt);
            }
        });

        lblLang.setText("Language");

        lblPages.setText("Pages");

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SN", "Name", "Author", "Registered", "Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBooks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPages, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPages, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(txtName)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLang))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLang)
                                    .addComponent(comboxAuthor, 0, 114, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthor)
                    .addComponent(comboxAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLang))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPages)
                    .addComponent(txtPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnAddBook)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboxAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxAuthorActionPerformed
        // TODO add your handling code here:
        if (this.comboxAuthor.getSelectedItem() == null) {
            return;
        }
        this.selectedAuthor = (Author) comboxAuthor.getSelectedItem();
    }//GEN-LAST:event_comboxAuthorActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        // TODO add your handling code here:
        String name = this.txtName.getText();
        String lang = this.txtName.getText();
        long pages = Long.parseLong(this.txtPages.getText());
        
        
        this.bookDirectory.newBook(name, lang, pages, selectedAuthor);
        
        this.txtName.setText("");
        this.txtLang.setText("");
        this.txtPages.setText("");
        
        this.refreshTable();
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel)tblBooks.getModel();
        model.setRowCount(0);
        
        int serialNum =1;
        
        for(Book b: this.bookDirectory.getBookList()) {
            Object[] obj = new Object[5];
            obj[0] = serialNum++;
            obj[1] = b.getBookName();
            obj[2] = b.getAuthor();
            obj[3] = b.getRegisteredDate();
            obj[4] = b.isIsRented() ? "Rented" : "Available";
            model.addRow(obj);
        }
    }
    
    private void populateAuthors() {
        comboxAuthor.removeAllItems();
        
        for(Author auth: this.authorDirectory.getAuthors()) {
            comboxAuthor.addItem(auth);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JComboBox<Author> comboxAuthor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblLang;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPages;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTextField txtLang;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPages;
    // End of variables declaration//GEN-END:variables
}
