/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.BranchManager;

import Library.Branches.Branch;
import Library.Library;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author gagan
 */
public class ControlPanelBranchManager extends javax.swing.JPanel {
    
    private JPanel mainWorkArea;
    private Branch branch;

    /**
     * Creates new form ControlPanelBranchManager
     */
    public ControlPanelBranchManager(JPanel mainWorkArea, Branch branch) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.branch = branch;
        this.openBooks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnBooks = new javax.swing.JButton();
        btnAuthors = new javax.swing.JButton();
        btnRentals = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        btnBooks.setText("Books");
        btnBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBooksActionPerformed(evt);
            }
        });

        btnAuthors.setText("Authors");
        btnAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorsActionPerformed(evt);
            }
        });

        btnRentals.setText("Rentals");
        btnRentals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalsActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBooks)
                    .addComponent(btnAuthors)
                    .addComponent(btnRentals)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(77, 77, 77)
                .addComponent(btnBooks)
                .addGap(38, 38, 38)
                .addComponent(btnAuthors)
                .addGap(41, 41, 41)
                .addComponent(btnRentals)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(workArea);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBooksActionPerformed
        // TODO add your handling code here:
        this.openBooks();
    }//GEN-LAST:event_btnBooksActionPerformed

    private void btnAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorsActionPerformed
        // TODO add your handling code here:
        AuthorsJPanel ajp = new AuthorsJPanel(this.branch.getLibrary().getAuthorDirectory());
        this.jSplitPane1.setRightComponent(ajp);
    }//GEN-LAST:event_btnAuthorsActionPerformed

    private void btnRentalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalsActionPerformed
        // TODO add your handling code here:
        RentalsJPanel rjp = new RentalsJPanel(this.branch.getLibrary().getRentalRecordDirectory());
        this.jSplitPane1.setRightComponent(rjp);
    }//GEN-LAST:event_btnRentalsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.mainWorkArea.remove(this);
        CardLayout layout = (CardLayout) this.mainWorkArea.getLayout();
        layout.previous(this.mainWorkArea);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void openBooks() {
        BooksJPanel booksJPanel = new BooksJPanel(this.branch.getLibrary().getBookDirectory(), this.branch.getLibrary().getAuthorDirectory());
        this.jSplitPane1.setRightComponent(booksJPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthors;
    private javax.swing.JButton btnBooks;
    private javax.swing.JButton btnRentals;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
