/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.BranchManager;

import Library.Author.Author;
import Rental.RentalRecord;
import Rental.RentalRecordDirectory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gagan
 */
public class RentalsJPanel extends javax.swing.JPanel {
    
    private RentalRecordDirectory directory;

    /**
     * Creates new form RentalsJPanel
     */
    public RentalsJPanel(RentalRecordDirectory directory) {
        initComponents();
        this.directory = directory;
        this.refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRentals = new javax.swing.JTable();

        tblRentals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Book", "Customer", "Rented", "Returned", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRentals);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel)tblRentals.getModel();
        model.setRowCount(0);
        
        for(RentalRecord rec: this.directory.getRentalRecords()) {
            Object[] obj = new Object[6];
            obj[0] = rec.getRecordId();
            obj[1] = rec.getBookName();
            obj[2] = rec.getCustomer();
            obj[3] = rec.getDatetimeRented().toString();
            obj[4] = rec.getDatetimeReturned() != null ? rec.getDatetimeReturned().toString() : "--";
            obj[5] = rec.isRentalStatus() ? "Pending" : "Returned";
                    
            model.addRow(obj);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRentals;
    // End of variables declaration//GEN-END:variables
}
